repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args:
          - "-r"
          - "backEnd/app"
          - "--exclude"
          - "../venv,../tests"
          - "--severity-level"
          - "medium"
          - "-f"
          - "json"
          - "-o"
          - "bandit-report.json"
          - "-v"
        pass_filenames: false
